### ISSUE TITLE
Ability to give pa11y scripts to run to get to areas of site for which I want to test assessibility

### ISSUE THREAD

**Issue by SamAlexand** [pa11y/sidekick#28]
The future idea of "Sites" and adding URL's to the site is cool and a step in right direction, and I think this idea can be taken further in terms of automation. Instead of manually specifying and dealing with potentially messy urls as part of a "Site", I want to record a script that goes through all the areas of the site for which we want to test accessibility, and have pa11y use the script to produce the report.

Perhaps pa11y can take a CasperJS script.  This would allow me to use something like
[resurrect](https://github.com/ebrehault/resurrectio) to record and produce script, then give it to pa11y.

As I iteratively develop my web app, I may want to upload a new script for pa11y to start using. Over time, I can track the violations in pa11y dashboard and hopefully see trends in the right direction.

**Comment by SamAlexand** [comment]
Just curious if there's any feedback on this idea and if my wording was clear. :-) Basically, the pa11y tools up to now seem geared more toward pointing them at a single URL with state.  There's other dynamic websites where you might need to navigate and take different actions to get to a page for which you want to test assessiblity, which is why I was asking about the ability to pass a script.
(Accidentally clicked the Close button a moment ago; sorry about that)

**Comment by rowanmanning** [comment]
Hey Sam, sorry haven't had chance to properly read this until now. I'd like to be able to do this definitely but it's probably more something that'd have to happen in [Pa11y](https://github.com/pa11y/pa11y) itself rather than be a Sidekick-specific thing (Sidekick will just use Pa11y under the hood).

I'll respond more fully soon, just letting you know that I have seen this. We'll probably end up opening a new issue on Pa11y to discuss 👍
